### ISSUE TITLE
Carousel flow on Firefox

### ISSUE THREAD

**Issue by cdefy** [Wlada/vue-carousel-3d#120]
Hi!

The carousel is working smoothly on Safari, Opera and Chrome but on Firefox there is like a glitch on one image when the slide turns. It looks like the glitch is only on the image with index 0 (the central one when the carousel is first displayed).

I tried different images, different configuration (scale, size, etc.) but the glitch still there.

Thanks for any feedbacks!

PS: there is a closed bug which might be related: #78

**Comment by januarfonti** [comment]
I also got the same problem on Firefox :( @cdefy any luck of this?

**Comment by cdefy** [comment]
Hi @januarfonti , I stopped using it for another reason. But don't remember it was fixed in between. :(

**Comment by Pranjalya** [comment]
If its still persistent, what's your Firefox version @cdefy and @januarfonti ? It's not visible in Firefox Developer version.

**Comment by cdefy** [comment]
Hi there, took me forever to come back and answer. At the time I didn't find the solution and I don't have this project anymore. Sorry!

@Pranjalya FYI I have the impressions sometimes that FF Dev Edition and FF don't always behave the same way.

**Comment by Wlada** [comment]
Not reproducible on v2.0.0 with Firefox 153 — during slide transitions the current slide stays visible, opacity 1 and centered once the animation ends, images load, and there are no JS errors (verified by frame sampling during 3 transitions). Reopen if you still see the glitch with a current version.
